"""drop_social_tables

Revision ID: 21503dcbd174
Revises: 322820c1d61e
Create Date: 2026-04-22 14:17:48.055869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21503dcbd174'
down_revision: Union[str, Sequence[str], None] = '322820c1d61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daily_record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('comments_author_id_fkey')),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_records.id'], name=op.f('comments_daily_record_id_fkey')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('comments_parent_comment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_table('reactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daily_record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_records.id'], name=op.f('reactions_daily_record_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reactions_pkey')),
    sa.UniqueConstraint('daily_record_id', 'user_id', 'emoji', name=op.f('uq_reaction_record_user_emoji'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
