"""add_teams_channel_config_to_admin_settings

Revision ID: 273daa92457e
Revises: b2c3d4e5f6a7
Create Date: 2026-04-22 13:53:40.924576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273daa92457e'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_sub_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin_settings', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.add_column('admin_settings', sa.Column('teams_channel_id', sa.String(), nullable=True))
    op.add_column('admin_settings', sa.Column('teams_team_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('admin_settings_key_key'), 'admin_settings', type_='unique')
    op.create_unique_constraint('uq_admin_settings_key_team', 'admin_settings', ['key', 'team_id'])
    op.create_foreign_key(None, 'admin_settings', 'teams', ['team_id'], ['id'])
    op.alter_column('daily_work_logs', 'energy_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('deep_focus', 'collaborative', 'admin', 'creative', 'reactive', name='energy_type', native_enum=False),
               existing_nullable=True)
    op.alter_column('daily_work_logs', 'insight',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('projects', 'github_repo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('p0_critical', 'p1_high', 'p2_medium', 'p3_low', name='task_priority', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('p0_critical', 'p1_high', 'p2_medium', 'p3_low', name='task_priority', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('projects', 'github_repo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_work_logs', 'insight',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('daily_work_logs', 'energy_type',
               existing_type=sa.Enum('deep_focus', 'collaborative', 'admin', 'creative', 'reactive', name='energy_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'admin_settings', type_='foreignkey')
    op.drop_constraint('uq_admin_settings_key_team', 'admin_settings', type_='unique')
    op.create_unique_constraint(op.f('admin_settings_key_key'), 'admin_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('admin_settings', 'teams_team_id')
    op.drop_column('admin_settings', 'teams_channel_id')
    op.drop_column('admin_settings', 'team_id')
    op.drop_table('category_sub_types')
    # ### end Alembic commands ###
