"""add_check_and_send_tracking_to_daily_records

Revision ID: fcdd7f228503
Revises: 21503dcbd174
Create Date: 2026-04-22 14:53:49.466740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdd7f228503'
down_revision: Union[str, Sequence[str], None] = '21503dcbd174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_records', sa.Column('is_checked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_records', sa.Column('teams_message_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_records', sa.Column('teams_message_id', sa.Text(), nullable=True))
    op.add_column('daily_records', sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_records', 'email_sent_at')
    op.drop_column('daily_records', 'teams_message_id')
    op.drop_column('daily_records', 'teams_message_sent_at')
    op.drop_column('daily_records', 'is_checked')
    # ### end Alembic commands ###
